twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    date:
        format: 'j M, Y - H:i'

when@test:
    twig:
        strict_variables: true
